repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        exclude: ^docs
      - id: check-added-large-files
        args:
          - --maxkb=1000
      - id: check-vcs-permalinks
      - id: check-merge-conflict
      - id: mixed-line-ending
        args:
          - --fix=lf
        exclude: ^docs
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 6.4.0
    hooks:
    -   id: buildifier
        args:
          - --warnings=all
    -   id: buildifier-lint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.3
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        exclude: ^examples/custom_converters/elu_converter/setup.py|^docs